### ISSUE TITLE
v1.0.0

### ISSUE THREAD

**Issue by locks** [emberjs/ember-string#2]
At the moment the package is named `at-ember-string`, because `@ember/string` wasn't working–possibly babel related–and I can't use `ember-string` because that's also one of the packages in `ember-cli-shims`.

# Tasks
- [x] Fix `index.js` exports name and tests
- [x] Make the [ember-cli-babel](https://github.com/babel/ember-cli-babel) not polyfill `@ember/string` if this addon is present: https://github.com/babel/ember-cli-babel/pull/176
- [x] Create another package to handle the prototype extension: https://github.com/locks/ember-string-prototype-extensions

**Comment by locks** [comment]
Published!
